name: Drata Compliance Scan

on:
  push:
    branches:
      - 'compliance/**'
  pull_request:
    branches:
      - main

jobs:
  drata-scan:
    name: Run Drata Compliance Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Drata Compliance Scan
        uses: drata/gh-action@v2
        with:
              drata-api-key: ${{ secrets.DRATA_API_KEYNEW }}
              severity-threshold: low
