name: Drata Compliance Scan

on:
  push:
    branches:
      - 'compliance/**'
  pull_request:
    branches:
      - main

jobs:
  drata-scan:
    name: Run Drata Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Drata Compliance Scan
        uses: drata/gh-action@v1
        env:
              DRATA_API_TOKEN: ${{ secrets.DRATA_IAC_PIPELINE_KEY }}
              GITHUB_REPOSITORY: $GITHUB_REPOSITORY
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          severity-threshold: low
         
